export const Config = {
    CANVAS_WIDTH: 1024,
    CANVAS_HEIGHT: 768,
    CELL_SIDE_LENGTH: 45,
    CELL_COLOR: 0xfbdd5d,
    CELL_BORDER_COLOR: 0xffffff,
    CELL_BORDER_SIZE: 1,
    DEFAULT_STORAGE_OBJECT_OFFSET: 5,
    TEXTURES: [
        {
            name: 'robot',
            url: '/media/robot.png'
        },
        {
            name: 'crate',
            url: '/media/crate.png'
        },
        {
            name: 'finish',
            url: '/media/finish.png'
        },
    ],
    ROBOTS_SPEED: 5,
    LOADING_SPEED: 0.02,
    LOADER_RADIUS: 30,
    LOADER_OFFSET: 20,
    INIT_DATA: {
        fieldWidth: 20,
        fieldHeight: 20,
        targetCells: [
            { x: 3, y: 19 },
            { x: 4, y: 19 },
            { x: 5, y: 19 },
            { x: 6, y: 19 },
            { x: 7, y: 19 },
            { x: 8, y: 19 },
            { x: 9, y: 19 },
            { x: 10, y: 19 },
            { x: 11, y: 19 },
            { x: 12, y: 19 },
            { x: 13, y: 19 },
            { x: 14, y: 19 },
            { x: 15, y: 19 },
            { x: 16, y: 19 },
        ],
        robots: [
            { x: 3, y: 19 },
            { x: 4, y: 19 },
            { x: 5, y: 19 },
            { x: 6, y: 19 },
            { x: 7, y: 19 },
            { x: 8, y: 19 },
            { x: 9, y: 19 },
            { x: 10, y: 19 },
            { x: 11, y: 19 },
            { x: 12, y: 19 },
            { x: 13, y: 19 },
            { x: 14, y: 19 },
            { x: 15, y: 19 },
            { x: 16, y: 19 },
        ],
    },
    MAP: [["crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate"],["crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate"],["crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate"],["crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate"],["crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate"],["crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate"],["crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate"],["crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate"],["crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate"],["crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate"],["crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate"],["crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate"],["crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate"],["crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate"],["crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate"],["crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate"],["crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate"],["crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate","crate","down","up","crate"],["crate","down","left","left","left","left","left","left","left","left","left","left","left","left","left","left","left","left","up","crate"],["crate","down","right","right","right","right","right","right","right","right","right","right","right","right","right","right","right","right","up","crate"]],
    CROSSROADS: [
        { x: 1, y: 19 },
        { x: 2, y: 19 },
        { x: 1, y: 18 },
        { x: 2, y: 18 },
        { x: 5, y: 19 },
        { x: 6, y: 19 },
        { x: 5, y: 18 },
        { x: 6, y: 18 },
        { x: 9, y: 19 },
        { x: 10, y: 19 },
        { x: 9, y: 18 },
        { x: 10, y: 18 },
        { x: 13, y: 19 },
        { x: 14, y: 19 },
        { x: 13, y: 18 },
        { x: 14, y: 18 },
        { x: 17, y: 19 },
        { x: 18, y: 19 },
        { x: 17, y: 18 },
        { x: 18, y: 18 },
    ],
    FAIL_LIMIT: 50,
};

export default Config;
